spring:
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/louisthomas/spring-cloud-config-repo
management:
  security:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/